### ISSUE TITLE
Recording doesn't start

### ISSUE THREAD

**Issue by buettiB** [TobitSoftware/clipinc#27]
It's not possible to start the recording. Error in console:

Error in event handler: TypeError: Cannot read properties of null (reading 'parentNode')
    at f (chrome-extension://oppggbgnmeainpanihcbcdniomfobmec/content/content.js:1:4331)
    at chrome-extension://oppggbgnmeainpanihcbcdniomfobmec/content/content.js:1:4831

Browser: Edge (OS: Mac & Win 11)

**Comment by duesentrieb26** [comment]
I can confirm this error
Version 116.0.5845.96 (Official Build) (arm64)

**Comment by tobistut** [comment]
I also can confirm this error; on both browser, Edge and Chrome

**Comment by hpoepping** [comment]
[This](https://github.com/TobitSoftware/clipinc/commit/ef3e310feef4452d5f330000bfcf6a4cee4243a9) should fix the issue.
New version (1.12.10) of the extension has been submitted to chrome web store and should be available soon.

**Comment by buettiB** [comment]
Thanks. Build the extension locally with the fix but still get an error. This time it's:

Error in event handler: TypeError: Cannot read properties of null (reading 'volume')
    at getVolume (chrome-extension://feahcgffjpdgehldgcgbikhljdomhjgl/content/content.js:325:57)
    at chrome-extension://feahcgffjpdgehldgcgbikhljdomhjgl/content/content.js:386:25

**Comment by buettiB** [comment]
Just saw that the Update is available in Chrome Store. Installed it from there and got the same issue as mentioned above.

**Comment by hpoepping** [comment]
The error seems to occur when the volume was never changed.
Should be fixed with version 1.12.11

**Comment by buettiB** [comment]
Build it locally and even with 1.12.11 it doesn't work. This time no error in console. Did multiple tries with installing/uninstalling of Clipinc and Browser-Cache reset but nothing did help.
Clipinc executed once prevents the browser form playing sound. After uninstalling Clipinc, sound works perfectly.
As I said console doesn't give any message. Is there anything else I can provide you with to get closer to the fix?
(Currently only tested on MacOS with Edge)

**Comment by buettiB** [comment]
1.12.11 is now available in Chrome Store. Installed it from there on Win 11 in Chrome Browser. Same behaviour as mentioned above: No recording but no error.

**Comment by buettiB** [comment]
Don't know how and why but the behaviour changed a little. Recording Window incates that it's recording but loads infinitaly. I build 1.12.11 locally and get a few errors in the extension view of Chrome:

clipinc: could not retrieve remote track info SyntaxError: Unexpected end of JSON input
content/content.js:262

and

Error in event handler: Error: Unknown command received: spotifyUpdateTrack
popup/index.html

In the Browser Console I see:

clipinc: could not retrieve remote track info SyntaxError: Unexpected end of JSON input
    at content.js:237:26

**Comment by KULTA** [comment]
> 1.12.11 is now available in Chrome Store. Installed it from there on Win 11 in Chrome Browser. Same behaviour as mentioned above: No recording but no error.

I can also confirm for Chrome on the MacBook Pro: You can't record with the latest version. In addition, after trying to record, you won't be able to hear anything if you try to start the player without recording. As a result, I copied the URL and opened it again (in a new tab). There I could hear something. I then pressed the record button again and heard nothing again, but clipinc showed a recording. Then I stopped the reccording and started the playing and recording again - and it works: I can record something. So it seems for me, that the tool still works but have some bugs.

**Comment by buettiB** [comment]
Did ist actually record something and downloaded the mp3? In my case it only seems like recording but nothing happened.

**Comment by KULTA** [comment]
It realy recorded a complete album and downloaded it as mp3. Then I tryed a second one but there was only one track downloaded (and that was the last one of the album). It seems that the titel of the album was to long, so there was no space for adding the tracks in the titel, so every new one overwrite an old one.

**Comment by hpoepping** [comment]
The function to automatically start playing the track when clicking on "start recording" did not work anymore. This caused that the extension could show the indicator for recording while doing nothing. Also if a track was already playing it showed the current track as being recorded but could not save it because the beginning was missing. Any subsequent tracks should have been working though. This should be fixed with the next version.

**Comment by buettiB** [comment]
This seems to fix the error now. Everything works as expected! Thanks for your support @hpoepping and thanks to the team for maintaining this free extension!
